### ISSUE TITLE
Disabled test are not mentioned after last update

### ISSUE THREAD

**Issue by oiaavb** [OneMoreGres/qtc-gtest#6]
After I updated to version 3.3.1 disabled tests seem no longer to be mentioned.

This is my test setup:
```c++
TEST(myTest, DISABLED_myCase0) {
	ASSERT_TRUE(true);
}

TEST(myTest, myCase1) {
	ASSERT_TRUE(true);
}
```

![05](https://cloud.githubusercontent.com/assets/8997015/6501344/5b572774-c317-11e4-87f3-a0ea2f5ea1a1.PNG)

**Comment by OneMoreGres** [comment]
Hi.
I got 2 news:
1. (Bad). Yes, it's broken
2. (Good). It's broken not because of the last update. It never worked that way :D
I hardcoded DISABLED TEST**S** match pattern. So it works fine for 2+ tests, but not 1 (~~now i've hardcoded DISABLED TEST :D~~).
Already fixed it anyway. Now ninja-updating binaries at sourceforge. Redownload version 3.3.1 and it should be fine.

**Comment by oiaavb** [comment]
Thank you :)
